fieldLayouts:
  2dabb977-1a59-45f8-bf8a-b0e821014c15:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T17:40:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e1eae73-a196-4c28-8027-46b1e89c5f5b # Lista Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 531a6fde-2c6d-41a8-b5af-56e1223775e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T18:07:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a220bd6-7d45-4cd3-9d88-7f3e583ed063 # Link CTA
            handle: linkPrivacyPolicy
            includeInCards: false
            instructions: null
            label: 'Link Privacy Policy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d033785-8645-4ede-b338-962ee8fef2ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T18:07:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a220bd6-7d45-4cd3-9d88-7f3e583ed063 # Link CTA
            handle: linkNoteLegali
            includeInCards: false
            instructions: null
            label: 'Link Note Legali'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f022840f-cd2a-43e7-aa59-892c24041788
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6aa789b1-01ca-4d11-bcd4-40979d1716ce
        userCondition: null
handle: navigazione
name: Navigazione
sortOrder: 2
