fieldLayouts:
  1059e71f-e91e-4765-895c-3ce6871615f0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-22T10:31:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0e998ccf-b819-41f0-88c2-01bfa99e19e2 # Orari
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a211aabe-547c-446e-9ab1-7775fd3fa616
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T10:31:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3673fc41-a579-4121-81bd-d598f59eca0a # Orario Ultimo Ingresso
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42119478-8531-4043-b8e4-cb408a6b35eb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T16:55:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ff59314d-d88c-469c-bb11-d18989180be0 # Icona Avviso Manutenzione
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 000b2bb9-a1a0-4bde-8642-00a57618929b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T16:55:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de834319-7a42-478c-9f63-192de7436f20 # Testo Avviso Manutenzione
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fd04f3c-a09a-4f83-8f91-a8090efec113
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 643c166d-8a1d-4a15-95f0-612955c5f587
        userCondition: null
handle: orariSettimanali
name: 'Orari Settimanali'
sortOrder: 1
