altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  6eea3406-ad24-4139-a27f-1a436f338122:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-21T11:23:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a8236654-4d7f-42c4-ac9b-ec8a89a2c986
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f6486c1-8a0e-44a5-a6dc-d97d7ad723bb
        userCondition: null
fs: uploads
handle: immagini
name: Immagini
sortOrder: 1
subpath: immagini
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
