altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  bc79064d-7f81-491a-9d9c-5f526a6ab7e0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-21T11:27:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 20300ee1-01c8-40be-ad1e-8bff5b107720
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b32fee4a-b785-4593-b641-8ec9e2ebd449
        userCondition: null
fs: uploads
handle: video
name: Video
sortOrder: 2
subpath: video
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
