color: null
description: null
fieldLayouts:
  20ea14d6-dcf6-4ad8-949d-eb72c1352994:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T17:44:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: anchorSezione
            includeInCards: false
            instructions: null
            label: 'Anchor Sezione'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8095f953-6715-41af-8bc0-cac69fb0b208
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:20:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: null
            includeInCards: true
            instructions: null
            label: Titolo
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eca70139-d2af-4f8d-80d5-902935f0f81a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:20:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46188251-46ab-4519-916a-28b77f5aabbe # Sottotitolo
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1e3dde6-de30-4663-a435-1b2cdb7d505e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:20:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ac4b2e80-4dbb-4a27-9fc5-9cb0a651a925 # Lista Info
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa846d16-d7af-4698-a749-77f630042dbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:22:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c16b2bdf-ca6d-44c6-ad1b-a1dc706a0368 # Switch
            handle: mappaVisibile
            includeInCards: false
            instructions: null
            label: 'Mappa Visibile'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90a6eaa8-6efe-4b9f-b319-2856bcfd6c16
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:22:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a220bd6-7d45-4cd3-9d88-7f3e583ed063 # Link CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 925d49a2-f95a-4773-a6a2-e38a519f766f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c9cb9e4-de46-4db3-bb1b-17020f546388
        userCondition: null
handle: comeRaggiungerci
hasTitleField: false
icon: null
name: 'Come Raggiungerci'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
