color: null
description: null
fieldLayouts:
  5cbca81a-d7b0-4930-abc6-8ca973ab3224:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T14:03:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: null
            includeInCards: true
            instructions: null
            label: Titolo
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 038658eb-97e3-48f7-be8c-a3f09a5b3289
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:03:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46188251-46ab-4519-916a-28b77f5aabbe # Sottotitolo
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe85ff9b-e33a-4093-ab5d-b076a19177bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T14:03:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ac4b2e80-4dbb-4a27-9fc5-9cb0a651a925 # Lista Info
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 967be471-d4a8-4519-8b96-8263e61b1e9d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64ba2c73-b60a-42ff-83f9-5cbc8f0ab14d
        userCondition: null
handle: faq
hasTitleField: false
icon: null
name: FAQ
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
