color: null
description: null
fieldLayouts:
  fdfed2e9-5260-4498-af0a-959d7357dbd7:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:4017fac0-2898-4409-ad1e-ec6249c689f6'
      - 'layoutElement:8a8999b5-fe5e-4226-9093-65d582264591'
      - 'layoutElement:d4c1a906-0f18-4a89-9e5a-507ca13c89ff'
      - 'layoutElement:7f0b6c56-6b6d-468c-8db8-50efb3a4a289'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-21T14:25:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4017fac0-2898-4409-ad1e-ec6249c689f6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T14:25:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4033fbd4-5d65-4515-96fd-2b54697b307d # Titolo Seconda Riga
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a8999b5-fe5e-4226-9093-65d582264591
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T14:25:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46188251-46ab-4519-916a-28b77f5aabbe # Sottotitolo
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4c1a906-0f18-4a89-9e5a-507ca13c89ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T14:25:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e10b9023-318a-4ed3-98ca-c905871af2b4 # Sottotitolo Seconda Riga
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f0b6c56-6b6d-468c-8db8-50efb3a4a289
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T14:25:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2fbf1bea-4c0f-4faf-b4df-d7c7faf27656 # Video Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a7056b8-5a93-4e11-b979-ddca12bf63ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T15:47:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ff59314d-d88c-469c-bb11-d18989180be0 # Icona Avviso Manutenzione
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f85adcd-9983-4bdd-83b4-b40299697ec5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T15:47:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: de834319-7a42-478c-9f63-192de7436f20 # Testo Avviso Manutenzione
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb0fb487-6cd3-42cf-acdd-fd5fc50078c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T15:47:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a220bd6-7d45-4cd3-9d88-7f3e583ed063 # Link CTA
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c7837c0-d6c7-4020-98eb-d25a07225f81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-21T13:57:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 61bded43-ec93-419c-a052-66062d3b33a5
            handle: titolo
            includeInCards: false
            instructions: null
            label: Titolo
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a39fbbec-1e9a-4b67-9a20-c8614b1a58bf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8289c216-05e0-4c73-8b21-b168d59c4ed4
        userCondition: null
handle: hero
hasTitleField: false
icon: null
name: Hero
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
