color: null
description: null
fieldLayouts:
  367ec76a-0042-4920-bb72-322c88397a2e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T17:40:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: null
            includeInCards: true
            instructions: null
            label: 'Titolo Link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d357fe5-b8e9-4c02-82b2-5286f3fda655
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T17:40:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: handleSezione
            includeInCards: true
            instructions: null
            label: 'Handle Sezione'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d71b7f3-52be-481b-bf7e-4ee98be8d9b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3734d7b8-1eb4-4337-b14d-d0475ef7e412
        userCondition: null
handle: linkInterno
hasTitleField: false
icon: null
name: 'Link Interno'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
