color: null
description: null
fieldLayouts:
  a191b071-c805-435d-8a4d-8e9e38056476:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-29T09:59:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: testoAvviso
            includeInCards: false
            instructions: null
            label: 'Testo avviso cambiamenti di orario'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8de6d903-7c0e-4e62-80c1-4d642bc0e926
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T09:59:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: titoloUltimoParagrafo
            includeInCards: false
            instructions: null
            label: 'Titolo Ultimo Paragrafo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4f0abb7-fefc-40e4-8d21-46db48ebccea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-29T09:59:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: ultimoParagrafo
            includeInCards: false
            instructions: null
            label: 'Ultimo Paragrafo'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 458c2b82-dedb-4610-aedf-2296b6413b11
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 597c17f0-33a3-4e97-88b4-70d91340c5ef
        userCondition: null
handle: schedaOrari
hasTitleField: false
icon: null
name: 'Scheda Orari Automatica'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
