color: null
description: null
fieldLayouts:
  86d80399-4779-43f4-8d37-90f469bd72f4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-23T17:42:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: anchorSezione
            includeInCards: false
            instructions: null
            label: 'Anchor Sezione'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a670188-2f75-43ec-af79-aa3c0cc13f29
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T11:33:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: aeb11d3b-b8f3-4a5a-b89e-309cead42890 # Titolo Prima Riga
            handle: null
            includeInCards: true
            instructions: null
            label: Titolo
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d69862f2-0a28-456d-8a2d-d4bd68742237
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T11:33:27+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46188251-46ab-4519-916a-28b77f5aabbe # Sottotitolo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf8b14fd-f17b-49b0-9f54-2c1de26ac35b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-23T18:41:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d11a92f6-c850-4eee-8622-7f2ae9da5cf0 # Componenti Testuali
            handle: cardOrari
            includeInCards: false
            instructions: null
            label: 'Card Orari'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b515424-4424-4a34-9717-2dbaad8e028d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T16:01:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53fb3da5-7c03-494f-bf94-ae71f1ac40d0 # Blocco di Testo
            handle: richTextBiglietti
            includeInCards: false
            instructions: null
            label: "Blocco di Testo Biglietti d'ingresso"
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b98f0d65-c090-4667-acc2-d43a013294fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T16:24:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53fb3da5-7c03-494f-bf94-ae71f1ac40d0 # Blocco di Testo
            handle: richTextSpiegazione
            includeInCards: false
            instructions: null
            label: 'Blocco di Testo Spiegazione'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5528d40c-9778-484c-af27-6e73d4bceb76
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-22T16:24:31+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 53fb3da5-7c03-494f-bf94-ae71f1ac40d0 # Blocco di Testo
            handle: richTextResidenti
            includeInCards: false
            instructions: null
            label: 'Testo per residenti'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bc8b0ff-8abd-4868-a4fa-9818af2a25b0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 63e947e7-0dc1-43e2-9dd7-66f8eacc8bec
        userCondition: null
handle: visita
hasTitleField: false
icon: null
name: Visita
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
