headingLevels:
  - 2
  - 3
  - 4
name: Simple
options:
  heading:
    options:
      -
        class: ck-heading_paragraph
        model: paragraph
        title: Paragraph
      -
        class: ck-heading_heading2
        model: heading2
        title: 'Heading 2'
        view: h2
      -
        class: ck-heading_heading3
        model: heading3
        title: 'Heading 3'
        view: h3
      -
        class: ck-heading_heading4
        model: heading4
        title: 'Heading 4'
        view: h4
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in new tab'
        mode: manual
  toolbar:
    items:
      - heading
      - '|'
      - bold
      - italic
      - underline
      - strikethrough
      - '|'
      - link
      - '|'
      - bulletedList
      - numberedList
      - '|'
      - blockQuote
      - '|'
      - undo
      - redo
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - '|'
  - link
  - '|'
  - bulletedList
  - numberedList
  - '|'
  - blockQuote
  - '|'
  - undo
  - redo
