columnSuffix: null
handle: linkCta
instructions: null
name: 'Link CTA'
searchable: false
settings:
  advancedFields:
    - target
    - title
    - ariaLabel
    - download
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - showUnpermittedSections
              - ''
            -
              - showUnpermittedEntries
              - ''
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - url
    - entry
    - asset
    - category
    - email
    - tel
    - sms
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
