columnSuffix: null
handle: listaImmagini
instructions: null
name: 'Lista Immagini'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:f91a0c15-40da-4ab6-a7d1-1f0dd212eaf4' # Immagini
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:f91a0c15-40da-4ab6-a7d1-1f0dd212eaf4' # Immagini
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: true
  showSearchInput: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:f91a0c15-40da-4ab6-a7d1-1f0dd212eaf4' # Immagini
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
