columnSuffix: null
handle: orarioUltimoIngresso
instructions: null
name: 'Orario Ultimo Ingresso'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: '21:00'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
