columnSuffix: null
handle: seoDescription
instructions: null
name: 'Seo Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: false
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
