dateModified: 1768576831
email:
  fromEmail: andrea@semplice.is
  fromName: fonta-trevi
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8f7f8686-4145-4205-ace1-e67e6e7f91f5: fonta-trevi # fonta-trevi
    9c5d5f1c-302b-432d-8889-3965d508b194: fonta-trevi # fonta-trevi
system:
  edition: solo
  live: true
  name: fonta-trevi
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
