isPublic: true
name: 'Public Schema'
scope:
  - 'sites.8f7f8686-4145-4205-ace1-e67e6e7f91f5:read' # Fontana Trevi - IT
  - 'sites.b2c3d4e5-f678-90ab-cdef-123456789012:read'
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.45952d02-8da9-45dc-81df-be4fea47ce47:read' # Homepage
  - 'nestedentryfields.53fb3da5-7c03-494f-bf94-ae71f1ac40d0:read' # Blocco di Testo
  - 'nestedentryfields.97c36746-feb8-4bc1-8b32-3e3c3259b31b:read' # Blocchi
  - 'nestedentryfields.ac4b2e80-4dbb-4a27-9fc5-9cb0a651a925:read' # Lista Info
  - 'volumes.f91a0c15-40da-4ab6-a7d1-1f0dd212eaf4:read' # Immagini
  - 'volumes.c0c8eabb-1d94-449c-b621-1252e3e75ea4:read' # Video
  - 'globalsets.85074937-dff7-4c16-9d2c-0c76875fea4a:read' # Orari Settimanali
